spring:
  application:
    name: banking-app

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres

  jpa:
    database-platform: postgres
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    com.company.bankingapp: DEBUG

server:
  port: 9999
  error:
    include-binding-errors: always
    include-exception: true
    include-message: always
    whitelabel:
      enabled: false

application:
  security:
    secret-key: diebrifbiebibciu3bcriub3f94h38hf8b4n9f
    expiration: 864000000

# Currency client properties
currency:
  apikey: S8mEhqOeIxymWxqgaFu4BqbL64tNhQtZ